import 'dart:async';

import 'package:liblsl_coordinator/liblsl_coordinator.dart';
import 'package:liblsl_coordinator/transports/lsl.dart';
import 'package:synchronized/synchronized.dart';

extension StreamDestroyMapExtension on Map<String, StreamInfoResource> {
  /// Disposes every resource in the map that discovery still owns.
  ///
  /// Resources that have been taken by a caller are skipped — freeing those
  /// would leave the new owner holding a dangling native pointer.
  void destroyOwned() {
    for (final resource in values) {
      if (resource.ownedByDiscovery) resource.dispose();
    }
  }

  /// Wraps and stores [streamInfos].
  void addAllStreamInfos(
    List<LSLStreamInfo> streamInfos, {
    required LslDiscovery manager,
    required String sessionName,
  }) {
    for (final info in streamInfos) {
      final resource = StreamInfoResource(
        streamInfo: info,
        manager: manager,
        sessionName: sessionName,
      );
      this[resource.id] = resource;
    }
  }
}

/// A peer discovered over LSL, together with the native `lsl_streaminfo` needed
/// to open an inlet to it.
///
/// Implements [PeerHandle] so the coordination layer can consume it without
/// knowing anything about LSL. See [PeerHandle] for why ownership transfer is
/// explicit — for this transport the underlying resource is a native pointer
/// that continuous discovery frees on its next cycle.
class StreamInfoResource extends LSLResource implements PeerHandle {
  StreamInfoResource({
    required this.streamInfo,
    required this.sessionName,
    super.manager,
  }) : super(id: 'stream-info') {
    create();
  }

  final LSLStreamInfo streamInfo;

  /// Session this resource was discovered under; used as a fallback when the
  /// peer's stream metadata does not carry one.
  final String sessionName;

  PeerDescriptor? _descriptor;
  bool _taken = false;

  @override
  String get id => 'lsl-streaminfo-${streamInfo.uid ?? streamInfo.streamName}';

  @override
  String? get description =>
      'LSL StreamInfo Resource for ${streamInfo.streamName} '
      '(id: ${streamInfo.uid})';

  /// The peer this stream belongs to.
  ///
  /// Built lazily: it requires serialising and parsing the stream's XML
  /// metadata, and most discovered streams are filtered out or already known,
  /// so paying that per stream per discovery cycle would be wasteful.
  @override
  PeerDescriptor get descriptor =>
      _descriptor ??= _buildDescriptor(streamInfo, sessionName);

  @override
  Object? get rawUnsafe => streamInfo;

  @override
  bool get ownedByDiscovery => !_taken && manager != null;

  @override
  bool get taken => _taken;

  @override
  void take() {
    if (disposed) {
      throw StateError('Cannot take a disposed peer handle ($id)');
    }
    if (_taken) {
      throw StateError(
        'Peer handle $id has already been taken; ownership can only transfer '
        'once',
      );
    }
    _taken = true;
    // Detach from discovery so its next cycle cannot free the streamInfo out
    // from under the new owner.
    manager?.releaseResource<StreamInfoResource>(id);
  }

  @override
  Future<void> create() async {
    await super.create();
  }

  @override
  Future<void> dispose() async {
    if (disposed) return;
    streamInfo.destroy();
    await super.dispose();
  }

  /// Reads the fields the LSL transport publishes into the stream's `desc`
  /// element, and combines them with the positional `source_id` encoding.
  static PeerDescriptor _buildDescriptor(
    LSLStreamInfo info,
    String sessionName,
  ) {
    final desc = _parseDescFields(info.toXml());
    // `source_id` is authoritative for identity; desc fills in the rest.
    // Fall back to desc if source_id is malformed rather than failing
    // discovery outright, since a peer we cannot parse should be ignored, not
    // fatal.
    try {
      final fromSourceId = PeerDescriptor.fromSourceId(
        info.sourceId,
        desc: {...desc, if (!desc.containsKey('session')) 'session': ''},
      );
      return fromSourceId.copyWith();
    } on FormatException {
      return PeerDescriptor(
        streamName: info.streamName,
        sessionName: desc['session'] ?? sessionName,
        nodeId: desc[LSLStreamInfoHelper.nodeIdKey] ?? '',
        nodeUId: desc[LSLStreamInfoHelper.nodeUIdKey] ?? info.sourceId,
        nodeRole:
            desc[LSLStreamInfoHelper.nodeRoleKey] ??
            NodeCapability.none.shortString,
        endpointId: info.sourceId,
      );
    }
  }

  /// Extracts `<key>value</key>` pairs from the stream's `desc` element.
  ///
  /// A regex rather than an XML parser: this runs at most once per discovered
  /// stream, the document is machine-generated by
  /// `LSLStreamInfoHelper.generateStreamInfo`, and the alternative is an XML
  /// dependency in the hot path of a latency-sensitive library.
  static Map<String, String> _parseDescFields(String xml) {
    const keys = [
      LSLStreamInfoHelper.sessionNameKey,
      LSLStreamInfoHelper.nodeIdKey,
      LSLStreamInfoHelper.nodeUIdKey,
      LSLStreamInfoHelper.nodeRoleKey,
      LSLStreamInfoHelper.nodeCapabilitiesKey,
      LSLStreamInfoHelper.randomRollKey,
      LSLStreamInfoHelper.nodeStartedAtKey,
    ];
    final result = <String, String>{};
    for (final key in keys) {
      final match = RegExp('<$key>(.*?)</$key>', dotAll: true).firstMatch(xml);
      if (match != null) result[key] = match.group(1)!;
    }
    return result;
  }
}

/// LSL-backed [IDiscovery].
///
/// Compiles each [DiscoveryQuery] to an XPath predicate (the only query
/// language LSL's resolver speaks) and re-resolves on a timer.
class LslDiscovery extends LSLResource implements IDiscovery, IResourceManager {
  LslDiscovery({
    required this.streamConfig,
    required this.coordinationConfig,
    required super.id,
    super.manager,
  });

  final NetworkStreamConfig streamConfig;
  final CoordinationConfig coordinationConfig;

  bool _paused = false;
  @override
  bool get paused => _paused;

  Timer? _discoveryInterval;
  Timer? _timeoutTimer;
  final Lock _discoveryLock = Lock();

  final Map<String, StreamInfoResource> _discoveredStreams = {};

  final StreamController<DiscoveryEvent> _eventController =
      StreamController<DiscoveryEvent>();

  @override
  Stream<DiscoveryEvent> get events => _eventController.stream;

  DiscoveryQuery? _currentQuery;
  String? _currentPredicate;
  LSLStreamResolverContinuous? _resolver;

  @override
  String get id => 'lsl-discovery-${streamConfig.id}';

  String get _sessionName => coordinationConfig.sessionConfig.name;

  @override
  void manageResource<R extends IResource>(R resource) {
    if (resource is! StreamInfoResource) {
      throw ArgumentError(
        'LslDiscovery can only manage StreamInfoResource instances, '
        'got ${resource.runtimeType}',
      );
    }
    resource.updateManager(this);
    _discoveredStreams[resource.id] = resource;
  }

  @override
  R releaseResource<R extends IResource>(String resourceUId) {
    final resource = _discoveredStreams.remove(resourceUId);
    if (resource == null) {
      throw ArgumentError('Resource with id $resourceUId not found');
    }
    resource.updateManager(null);
    return resource as R;
  }

  void _ensureCreated() {
    if (!created || disposed) {
      throw StateError('Discovery resource is not created');
    }
  }

  @override
  Future<void> create() async {
    if (created) return;
    await super.create();
  }

  @override
  void start({
    required DiscoveryQuery query,
    Duration? timeout,
    int? maxPeers,
  }) {
    _ensureCreated();
    final predicate = LslPredicateCompiler.compile(query);

    if (_currentPredicate != predicate || _resolver == null) {
      stop();
      _currentQuery = query;
      _currentPredicate = predicate;
      logger.finest('Creating new resolver for predicate: $predicate');
      _resolver = LSLStreamResolverContinuousByPredicate(
        predicate: predicate,
        maxStreams: maxPeers ?? coordinationConfig.topologyConfig.maxNodes,
        forgetAfter:
            coordinationConfig.sessionConfig.nodeTimeout.inMilliseconds /
            1000.0,
      );
      _resolver!.create();
    }

    if (timeout != null) {
      _timeoutTimer?.cancel();
      _timeoutTimer = Timer(timeout, () {
        if (disposed || !created) return;
        _eventController.add(DiscoveryTimeoutEvent(query, timeout));
      });
    }

    _startContinuousDiscovery();
  }

  @override
  void stop() {
    logger.fine('Stopping discovery');
    _discoveryInterval?.cancel();
    _discoveryInterval = null;
    _timeoutTimer?.cancel();
    _timeoutTimer = null;
    _resolver?.destroy();
    _resolver = null;
  }

  Future<void> _startContinuousDiscovery() async {
    if (_resolver == null) return;

    _discoveryInterval?.cancel();
    _discoveryInterval = Timer.periodic(
      coordinationConfig.sessionConfig.discoveryInterval,
      (_) async {
        if (_paused || disposed) return;
        await _performContinuousDiscovery();
      },
    );
    await _performContinuousDiscovery();
  }

  Future<void> _performContinuousDiscovery() async {
    if (_resolver == null || _currentQuery == null || disposed || !created) {
      return;
    }

    return _discoveryLock.synchronized(() async {
      if (disposed || !created) return;

      try {
        // Free the previous cycle's resources — except any a caller has taken
        // ownership of, which are no longer ours to free.
        _discoveredStreams.destroyOwned();
        _discoveredStreams.clear();

        final newStreams = await _resolver!.resolve();
        logger.finest('Resolver returned ${newStreams.length} stream(s)');

        _discoveredStreams.addAllStreamInfos(
          newStreams,
          manager: this,
          sessionName: _sessionName,
        );

        if (newStreams.isNotEmpty) {
          _timeoutTimer?.cancel();
          _timeoutTimer = null;
          _eventController.add(
            PeersDiscoveredEvent(
              _currentQuery!,
              _discoveredStreams.values.toList(growable: false),
            ),
          );
        }
      } catch (e) {
        logger.warning('Discovery error for predicate $_currentPredicate: $e');
      }
    });
  }

  @override
  void pause() {
    _ensureCreated();
    if (_paused) return;
    _paused = true;
    _discoveryInterval?.cancel();
  }

  @override
  void resume() {
    _ensureCreated();
    if (!_paused) return;
    _paused = false;
    _startContinuousDiscovery();
  }

  @override
  Future<List<PeerHandle>> discoverOnce(
    DiscoveryQuery query, {
    Duration timeout = const Duration(seconds: 2),
    int minPeers = 0,
    int maxPeers = 10,
  }) async {
    final streamInfos = await discoverOnceByPredicate(
      LslPredicateCompiler.compile(query),
      timeout: timeout,
      minStreams: minPeers,
      maxStreams: maxPeers,
    );
    // Deliberately unmanaged: one-shot results belong to the caller, so
    // `manager` is null and `take()` is a no-op on them.
    return streamInfos
        .map(
          (info) =>
              StreamInfoResource(streamInfo: info, sessionName: _sessionName),
        )
        .toList(growable: false);
  }

  /// One-shot resolve against a raw XPath predicate.
  ///
  /// Runs in an isolate so the blocking FFI resolve does not stall the event
  /// loop. The caller owns the returned [LSLStreamInfo]s and must destroy them.
  static Future<List<LSLStreamInfo>> discoverOnceByPredicate(
    String predicate, {
    Duration timeout = const Duration(seconds: 2),
    int minStreams = 0,
    int maxStreams = 10,
  }) async {
    final streams = await IsolateStreamManager.discoverOnceIsolated(
      predicate: predicate,
      timeout: timeout,
      minStreams: minStreams,
      maxStreams: maxStreams,
    );
    logger.finer(
      'One-time discovery found ${streams.length} stream(s) for predicate: '
      '$predicate',
    );
    return streams;
  }

  @override
  Future<void> dispose() async {
    if (disposed) return;
    logger.fine('Disposing LSL discovery');
    stop();
    await _discoveryLock.synchronized(() async {
      if (disposed) return;
      await super.dispose();

      // Not awaited: the single subscriber has already been cancelled, so
      // close()'s future would never complete.
      logger.finest('Closing discovery event controller');
      unawaited(_eventController.close());

      logger.finest('Destroying discovered streams');
      _discoveredStreams.destroyOwned();
      _discoveredStreams.clear();
    });
  }
}
