name: serial_transport
description: Single serial port transport shim for liblsl.dart.
version: 0.1.0
homepage: https://zeyus.com/
repository: https://github.com/NexusDynamic/liblsl.dart
issue_tracker: https://github.com/NexusDynamic/liblsl.dart/issues

resolution: workspace

environment:
  sdk: ^3.10.0

dependencies:
  code_assets: ^2.0.0
  ffi: ^2.1.4
  hooks: ^2.0.0
  logging: ^1.3.0
  native_toolchain_c: ^0.19.4
  web: ^1.1.0

dev_dependencies:
  ffigen: ^22.0.0
  lints: ^6.0.0
  test: ^1.28.0
