name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: beta
        cache: true
        cache-key: "flutter-:os:-:channel:-:version:-:arch:-{{ github.head_ref || github.ref_name }}"
        pub-cache-key: "flutter-pub-:os:-:channel:-:version:-:arch:-{{ github.head_ref || github.ref_name }}"

    - name: Install melos
      run: dart pub global activate melos

    - name: Bootstrap packages
      run: melos bootstrap

    - name: Analyze code
      run: melos run analyze

    - name: Check formatting
      run: melos run format-check

    - name: Run tests
      run: melos run test
